### ISSUE TITLE
ConcurrentModificationException while resetting team config

### ISSUE THREAD

**Issue by efibs** [efibs/mc-lasertag-mod#203]
java.util.ConcurrentModificationException: null

	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:?]

	at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:?]

	at de.kleiner3.lasertag.lasertaggame.management.team.LasertagTeamManager.forEachPlayer(LasertagTeamManager.java:67) ~[lasertag-mod-0.4.0pre2.jar:?]

	at de.kleiner3.lasertag.networking.server.callbacks.ClientTriggerResetTeamConfigCallback.lambda$receive$2(ClientTriggerResetTeamConfigCallback.java:33) ~[lasertag-mod-0.4.0pre2.jar:?]

	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]

	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]

	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]

	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]

	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]

	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]

	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]

	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]

	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]

	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[server-intermediary.jar:?]

	at net.minecraft.server.MinecraftServer.handler$zbe000$carpet$modifiedRunLoop(MinecraftServer.java:3394) ~[server-intermediary.jar:?]

	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]

	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]

	at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by efibs** [comment]
Not reproducible anymore. Maybe fixed with #213
