### ISSUE TITLE
Exception at point hunter end

### ISSUE THREAD

**Issue by efibs** [efibs/mc-lasertag-mod#249]
java.lang.RuntimeException: Failed to load class file for 'de.kleiner3.lasertag.lasertaggame.gamemode.implementation.PointHunterGameMode$PointHunterScore'!

	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:457) ~[fabric-loader-0.15.7.jar:?]

	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.15.7.jar:?]

	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.7.jar:?]

	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]

	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]

	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]

	at de.kleiner3.lasertag.lasertaggame.gamemode.implementation.PointHunterGameMode.getPlayerFinalScore(PointHunterGameMode.java:72) ~[lasertag-mod-0.4.0pre2.jar:?]

	at de.kleiner3.lasertag.lasertaggame.statistics.StatsCalculator.calcStats(StatsCalculator.java:53) ~[lasertag-mod-0.4.0pre2.jar:?]

	at de.kleiner3.lasertag.lasertaggame.state.management.server.implementation.ServerLasertagManager.generateStats(ServerLasertagManager.java:529) [lasertag-mod-0.4.0pre2.jar:?]

	at de.kleiner3.lasertag.lasertaggame.state.management.server.implementation.ServerLasertagManager.lasertagGameOver(ServerLasertagManager.java:520) [lasertag-mod-0.4.0pre2.jar:?]

	at de.kleiner3.lasertag.lasertaggame.state.management.server.implementation.ServerLasertagManager.endTick(ServerLasertagManager.java:405) [lasertag-mod-0.4.0pre2.jar:?]

	at de.kleiner3.lasertag.lasertaggame.timing.GameTickTimerTask.run(GameTickTimerTask.java:57) [lasertag-mod-0.4.0pre2.jar:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]

	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:?]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]

	at java.lang.Thread.run(Unknown Source) [?:?]

Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)

	at java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(Unknown Source) ~[?:?]

	at java.util.zip.ZipFile$ZipFileInputStream.read(Unknown Source) ~[?:?]

	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(Unknown Source) ~[?:?]

	at java.util.zip.InflaterInputStream.read(Unknown Source) ~[?:?]

	at java.io.FilterInputStream.read(Unknown Source) ~[?:?]

	at java.io.FilterInputStream.read(Unknown Source) ~[?:?]

	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getRawClassByteArray(KnotClassDelegate.java:501) ~[fabric-loader-0.15.7.jar:?]

	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:455) ~[fabric-loader-0.15.7.jar:?]

	... 17 more

**Comment by efibs** [comment]
Not reproducible anymore
